// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhktlhhjxxtxbmayarat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa3RsaGhqeHh0eGJtYXlhcmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTAyMzAsImV4cCI6MjA1NTI4NjIzMH0.bUi3CQE4ZmbFpjlM4rUx60yaQjwwn8xU2uFciEWxZo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);